apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ledgerops

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - account-service.yaml
  - fraud-service.yaml
  - transaction-service.yaml
